local:
    project_name: "ds"
    # Ex: <project_name> - "django"

    project_root: "/home/mp/ds"
    # Ex: <path_to_your_project_directory> - "/home/Workspace/Projects/Django"

    env_path: "/home/mp/ds/env"
    # Ex: <env_path> - "/home/Workspace/Projects/Django/env"

    repository_root: "/home/mp/ds/ds"
    # Ex: <path_to_your_project> - "/home/Workspace/Projects/Django/django"

    requirements_file: "/home/mp/ds/ds/requirements.txt"
    # Ex: <requirements_file_path> - "/home/Workspace/Projects/Django/django/requirements.txt"

    db_name: "ds"

    db_username: "root"

    database: "mysql"
    # Options: mysql/postgres

live:
    servers: ['136.243.86.117']
    # Ex: ['username@hostname:port']

    project_name: "ds"

    project_root: "/home/ds"

    env_path: "/home/ds/env"

    repository_root: "/home/ds/ds"

    requirements_file: "/home/ds/ds/requirements.txt"

    uwsgi_file_path: "/home/ds"
    # Ex: "/home/Workspace/Projects/Django/"

    uwsgi_file: "ds_uwsgi.ini"
    # Ex: "django_uwsgi.ini"

    db_name: "ds"

    db_username: "root"

    database: "mysql"

stage:
    servers: []

    project_name: ""

    project_root: ""

    env_path: ""

    repository_root: ""

    requirements_file: ""

    uwsgi_file_path: ""

    uwsgi_file: ""

    db_name: ""

    db_username: ""

    database: ""

